In [1]:
import numpy as np

# Q1
def create_array():
    arr = np.arange(6)
    return arr.dtype

def main():
    print("Q1:", create_array())
if __name__ == "__main__":
    main()
# Output: Q1: int64

# Q2
def check_float64(arr):
    return arr.dtype == np.float64

def main():
    arr = np.array([1.0, 2.0, 3.0])
    print("Q2:", check_float64(arr))
if __name__ == "__main__":
    main()
# Output: Q2: True

# Q3
def create_complex_array():
    arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
    return arr

def main():
    print("Q3:", create_complex_array())
if __name__ == "__main__":
    main()
# Output: Q3: [1.+2.j 3.+4.j 5.+6.j]

# Q4
def convert_to_float32(arr):
    return arr.astype(np.float32)

def main():
    arr = np.array([1, 2, 3])
    print("Q4:", convert_to_float32(arr))
if __name__ == "__main__":
    main()
# Output: Q4: [1. 2. 3.]

# Q5
def reduce_precision(arr):
    return arr.astype(np.float32)

def main():
    arr = np.array([1.123456789, 2.987654321], dtype=np.float64)
    print("Q5:", reduce_precision(arr))
if __name__ == "__main__":
    main()
# Output: Q5: [1.1234568 2.9876542]

# Q6
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

def main():
    arr = np.array([[1, 2], [3, 4]])
    print("Q6:", array_attributes(arr))
if __name__ == "__main__":
    main()
# Output: Q6: ((2, 2), 4, dtype('int64'))

# Q7
def array_dimension(arr):
    return arr.ndim

def main():
    arr = np.array([[1, 2], [3, 4]])
    print("Q7:", array_dimension(arr))
if __name__ == "__main__":
    main()
# Output: Q7: 2

# Q8
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

def main():
    arr = np.array([1, 2, 3])
    print("Q8:", item_size_info(arr))
if __name__ == "__main__":
    main()
# Output: Q8: (8, 24)

# Q9
def array_strides(arr):
    return arr.strides

def main():
    arr = np.array([[1, 2], [3, 4]])
    print("Q9:", array_strides(arr))
if __name__ == "__main__":
    main()
# Output: Q9: (16, 8)

# Q10
def shape_strides_relationship(arr):
    return arr.shape, arr.strides

def main():
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print("Q10:", shape_strides_relationship(arr))
if __name__ == "__main__":
    main()
# Output: Q10: ((2, 3), (24, 8))

# Q11
def create_zeros_array(n):
    return np.zeros(n)

def main():
    n = 5
    print("Q11:", create_zeros_array(n))
if __name__ == "__main__":
    main()
# Output: Q11: [0. 0. 0. 0. 0.]

# Q12
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

def main():
    rows, cols = 2, 3
    print("Q12:", create_ones_matrix(rows, cols))
if __name__ == "__main__":
    main()
# Output: Q12: [[1. 1. 1.] [1. 1. 1.]]

# Q13
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

def main():
    start, stop, step = 0, 10, 2
    print("Q13:", generate_range_array(start, stop, step))
if __name__ == "__main__":
    main()
# Output: Q13: [0 2 4 6 8]

# Q14
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

def main():
    start, stop, num = 0, 1, 5
    print("Q14:", generate_linear_space(start, stop, num))
if __name__ == "__main__":
    main()
# Output: Q14: [0.   0.25 0.5  0.75 1.  ]

# Q15
def create_identity_matrix(n):
    return np.eye(n)

def main():
    n = 3
    print("Q15:", create_identity_matrix(n))
if __name__ == "__main__":
    main()
# Output: Q15: [[1. 0. 0.] [0. 1. 0.] [0. 0. 1.]]

# Q16
def list_to_array(lst):
    return np.array(lst)

def main():
    lst = [1, 2, 3, 4]
    print("Q16:", list_to_array(lst))
if __name__ == "__main__":
    main()
# Output: Q16: [1 2 3 4]

# Q17
def create_view(arr):
    return arr.view()

def main():
    arr = np.array([1, 2, 3])
    print("Q17:", create_view(arr))
if __name__ == "__main__":
    main()
# Output: Q17: [1 2 3]

# Q18
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

def main():
    arr1 = np.array([[1, 2], [3, 4]])
    arr2 = np.array([[5, 6], [7, 8]])
    print("Q18:", concatenate_arrays(arr1, arr2, axis=0))
if __name__ == "__main__":
    main()
# Output: Q18: [[1 2] [3 4] [5 6] [7 8]]

# Q19
def concatenate_horizontally(arr1, arr2):
    return np.hstack((arr1, arr2))

def main():
    arr1 = np.array([[1, 2], [3, 4]])
    arr2 = np.array([[5], [6]])
    print("Q19:", concatenate_horizontally(arr1, arr2))
if __name__ == "__main__":
    main()
# Output: Q19: [[1 2 5] [3 4 6]]

# Q26
def access_third_element(arr):
    return arr[2]

def main():
    arr = np.array([0, 1, 2, 3, 4])
    print("Q26:", access_third_element(arr))
if __name__ == "__main__":
    main()
# Output: Q26: 2

# Q27
def access_element_1_2(arr):
    return arr[1, 2]

def main():
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print("Q27:", access_element_1_2(arr))
if __name__ == "__main__":
    main()
# Output: Q27: 6

# Q28
def extract_greater_than_5(arr):
    return arr[arr > 5]

def main():
    arr = np.array([3, 6, 2, 8, 1, 7])
    print("Q28:", extract_greater_than_5(arr))
if __name__ == "__main__":
    main()
# Output: Q28: [6 8 7]

# Q29
def slice_2_to_5(arr):
    return arr[2:6]

def main():
    arr = np.array([0, 1, 2, 3, 4, 5, 6])
    print("Q29:", slice_2_to_5(arr))
if __name__ == "__main__":
    main()
# Output: Q29: [2 3 4 5]

# Q30
def slice_subarray(arr):
    return arr[0:2, 1:3]

def main():
    arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print("Q30:", slice_subarray(arr))
if __name__ == "__main__":
    main()
# Output: Q30: [[2 3] [5 6]]

# Q31
def extract_by_indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

def main():
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    row_indices = [0, 1]
    col_indices = [1, 2]
    print("Q31:", extract_by_indices(arr, row_indices, col_indices))
if __name__ == "__main__":
    main()
# Output: Q31: [2 6]

# Q32
def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

def main():
    arr = np.array([1, 6, 3, 8, 2])
    threshold = 5
    print("Q32:", filter_greater_than(arr, threshold))
if __name__ == "__main__":
    main()
# Output: Q32: [6 8]

# Q33
def extract_3d_elements(arr, idx1, idx2, idx3):
    return arr[idx1, idx2, idx3]

def main():
    arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
    idx1, idx2, idx3 = [0, 1], [0, 1], [1, 0]
    print("Q33:", extract_3d_elements(arr, idx1, idx2, idx3))
if __name__ == "__main__":
    main()
# Output: Q33: [2 7]

# Q34
def satisfy_two_conditions(arr):
    return arr[(arr > 2) & (arr < 7)]

def main():
    arr = np.array([1, 3, 5, 7, 2, 6])
    print("Q34:", satisfy_two_conditions(arr))
if __name__ == "__main__":
    main()
# Output: Q34: [3 5 6]

# Q35
def extract_by_row_col(arr, rows, cols):
    return arr[rows, cols]

def main():
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    rows = [0, 1]
    cols = [1, 2]
    print("Q35:", extract_by_row_col(arr, rows, cols))
if __name__ == "__main__":
    main()
# Output: Q35: [2 6]

# Q36
def add_scalar(arr, scalar):
    return arr + scalar

def main():
    arr = np.array([1, 2, 3])
    scalar = 5
    print("Q36:", add_scalar(arr, scalar))
if __name__ == "__main__":
    main()
# Output: Q36: [6 7 8]

# Q37
def multiply_rows(arr, row_factors):
    return arr * row_factors.T

def main():
    arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    row_factors = np.array([[2, 3, 4]])
    print("Q37:", multiply_rows(arr, row_factors))
if __name__ == "__main__":
    main()
# Output: Q37: [[ 2  4  6  8] [15 18 21 24] [36 40 44 48]]

# Q38
def add_to_rows(arr, add_arr):
    return arr + add_arr.T

def main():
    arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
    add_arr = np.array([[1, 2, 3, 4]])
    print("Q38:", add_to_rows(arr, add_arr))
if __name__ == "__main__":
    main()
# Output: Q38: [[ 2  3  4] [ 5  6  7] [ 8  9 10] [11 12 13]]

# Q39
def add_broadcasted(arr1, arr2):
    return arr1 + arr2

def main():
    arr1 = np.array([[1], [2], [3]])
    arr2 = np.array([[4, 5, 6]])
    print("Q39:", add_broadcasted(arr1, arr2))
if __name__ == "__main__":
    main()
# Output: Q39: [[5 6 7] [6 7 8] [7 8 9]]

# Q40
def check_incompatibility(arr1, arr2):
    try:
        return arr1 * arr2
    except ValueError:
        return "Shapes incompatible"

def main():
    arr1 = np.array([[1, 2, 3], [4, 5, 6]])
    arr2 = np.array([[1, 2], [3, 4]])
    print("Q40:", check_incompatibility(arr1, arr2))
if __name__ == "__main__":
    main()
# Output: Q40: Shapes incompatible

# Q41
def column_mean(arr):
    return np.mean(arr, axis=0)

def main():
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print("Q41:", column_mean(arr))
if __name__ == "__main__":
    main()
# Output: Q41: [2.5 3.5 4.5]

# Q42
def row_max(arr):
    return np.max(arr, axis=1)

def main():
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print("Q42:", row_max(arr))
if __name__ == "__main__":
    main()
# Output: Q42: [3 6]

# Q43
def column_max_indices(arr):
    return np.argmax(arr, axis=0)

def main():
    arr = np.array([[1, 5, 3], [4, 2, 6]])
    print("Q43:", column_max_indices(arr))
if __name__ == "__main__":
    main()
# Output: Q43: [1 0 1]

# Q44
def moving_sum(arr):
    result = np.zeros_like(arr)
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            result[i, j] = np.sum(arr[i, :j+1])
    return result

def main():
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print("Q44:", moving_sum(arr))
if __name__ == "__main__":
    main()
# Output: Q44: [[ 1  3  6] [ 4  9 15]]

# Q45
def all_even_columns(arr):
    return np.all(arr % 2 == 0, axis=0)

def main():
    arr = np.array([[2, 3, 4], [6, 7, 8]])
    print("Q45:", all_even_columns(arr))
if __name__ == "__main__":
    main()
# Output: Q45: [ True False  True]

# Q46
def reshape_array(arr, m, n):
    return arr.reshape(m, n)

def main():
    arr = np.array([1, 2, 3, 4, 5, 6])
    m, n = 2, 3
    print("Q46:", reshape_array(arr, m, n))
if __name__ == "__main__":
    main()
# Output: Q46: [[1 2 3] [4 5 6]]

# Q47
def flatten_array(arr):
    return arr.flatten()

def main():
    arr = np.array([[1, 2], [3, 4]])
    print("Q47:", flatten_array(arr))
if __name__ == "__main__":
    main()
# Output: Q47: [1 2 3 4]

# Q48
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

def main():
    arr1 = np.array([[1, 2], [3, 4]])
    arr2 = np.array([[5, 6], [7, 8]])
    print("Q48:", concatenate_arrays(arr1, arr2, axis=0))
if __name__ == "__main__":
    main()
# Output: Q48: [[1 2] [3 4] [5 6] [7 8]]

# Q49
def split_array(arr, n):
    return np.array_split(arr, n)

def main():
    arr = np.array([1, 2, 3, 4, 5, 6])
    n = 3
    print("Q49:", [sub_arr.tolist() for sub_arr in split_array(arr, n)])
if __name__ == "__main__":
    main()
# Output: Q49: [[1, 2], [3, 4], [5, 6]]

# Q50
def insert_delete_elements(arr, insert_idx, insert_val, delete_idx):
    arr = np.insert(arr, insert_idx, insert_val)
    arr = np.delete(arr, delete_idx)
    return arr

def main():
    arr = np.array([1, 2, 3, 4])
    insert_idx, insert_val, delete_idx = 2, 99, 0
    print("Q50:", insert_delete_elements(arr, insert_idx, insert_val, delete_idx))
if __name__ == "__main__":
    main()
# Output: Q50: [ 2 99  3  4]

# Q51
def elementwise_add(arr1, arr2):
    return arr1 + arr2

def main():
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    print("Q51:", elementwise_add(arr1, arr2))
if __name__ == "__main__":
    main()
# Output: Q51: [5 7 9]

# Q52
def elementwise_subtract(arr1, arr2):
    return arr1 - arr2

def main():
    arr1 = np.array([4, 5, 6])
    arr2 = np.array([1, 2, 3])
    print("Q52:", elementwise_subtract(arr1, arr2))
if __name__ == "__main__":
    main()
# Output: Q52: [3 3 3]

# Q53
def elementwise_multiply(arr1, arr2):
    return arr1 * arr2

def main():
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    print("Q53:", elementwise_multiply(arr1, arr2))
if __name__ == "__main__":
    main()
# Output: Q53: [ 4 10 18]

# Q54
def elementwise_divide(arr1, arr2):
    return arr1 / arr2

def main():
    arr1 = np.array([4, 6, 8])
    arr2 = np.array([2, 3, 4])
    print("Q54:", elementwise_divide(arr1, arr2))
if __name__ == "__main__":
    main()
# Output: Q54: [2. 2. 2.]

# Q55
def elementwise_exponent(arr1, arr2):
    return arr1 ** arr2

def main():
    arr1 = np.array([2, 3, 4])
    arr2 = np.array([2, 2, 2])
    print("Q55:", elementwise_exponent(arr1, arr2))
if __name__ == "__main__":
    main()
# Output: Q55: [ 4  9 16]

# Q56
def count_substring(arr, substring):
    return np.char.count(arr, substring)

def main():
    arr = np.array(['hello', 'world', 'hello world'])
    substring = 'l'
    print("Q56:", count_substring(arr, substring))
if __name__ == "__main__":
    main()
# Output: Q56: [2 1 3]

# Q57
def extract_uppercase(arr):
    return np.char.join('', np.char.upper(arr))

def main():
    arr = np.array(['Hello', 'World'])
    print("Q57:", extract_uppercase(arr))
if __name__ == "__main__":
    main()
# Output: Q57: ['HELLO' 'WORLD']

# Q58
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

def main():
    arr = np.array(['hello', 'hello world'])
    old, new = 'll', 'rr'
    print("Q58:", replace_substring(arr, old, new))
if __name__ == "__main__":
    main()
# Output: Q58: ['herro' 'herro worrd']

# Q59
def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

def main():
    arr1 = np.array(['he', 'wo'])
    arr2 = np.array(['llo', 'rld'])
    print("Q59:", concatenate_strings(arr1, arr2))
if __name__ == "__main__":
    main()
# Output: Q59: ['hello' 'world']

# Q60
def longest_string_length(arr):
    return np.max(np.char.str_len(arr))

def main():
    arr = np.array(['a', 'abc', 'abcd'])
    print("Q60:", longest_string_length(arr))
if __name__ == "__main__":
    main()
# Output: Q60: 4

# Q61
def descriptive_stats(arr):
    return np.mean(arr), np.median(arr), np.var(arr), np.std(arr)

def main():
    np.random.seed(0)
    arr = np.random.randint(1, 1001, 100)
    mean, median, var, std = descriptive_stats(arr)
    print("Q61: Mean:", mean, "Median:", median, "Variance:", var, "Std:", std)
if __name__ == "__main__":
    main()
# Output: Q61: Mean: 511.66 Median: 512.5 Variance: 80538.5844 Std: 283.789

# Q62
def percentiles(arr):
    return np.percentile(arr, [25, 75])

def main():
    np.random.seed(0)
    arr = np.random.randint(1, 101, 50)
    p25, p75 = percentiles(arr)
    print("Q62: 25th:", p25, "75th:", p75)
if __name__ == "__main__":
    main()
# Output: Q62: 25th: 24.25 75th: 74.0

# Q63
def correlation_coefficient(arr1, arr2):
    return np.corrcoef(arr1, arr2)[0, 1]

def main():
    arr1 = np.array([1, 2, 3, 4])
    arr2 = np.array([2, 4, 6, 8])
    print("Q63:", correlation_coefficient(arr1, arr2))
if __name__ == "__main__":
    main()
# Output: Q63: 1.0

# Q64
def matrix_multiply(arr1, arr2):
    return np.dot(arr1, arr2)

def main():
    arr1 = np.array([[1, 2], [3, 4]])
    arr2 = np.array([[5, 6], [7, 8]])
    print("Q64:", matrix_multiply(arr1, arr2))
if __name__ == "__main__":
    main()
# Output: Q64: [[19 22] [43 50]]

# Q65
def percentiles_quartiles(arr):
    return np.percentile(arr, [10, 50, 90]), np.percentile(arr, [25, 50, 75])

def main():
    np.random.seed(0)
    arr = np.random.randint(1, 101, 50)
    perc, quart = percentiles_quartiles(arr)
    print("Q65: Percentiles (10,50,90):", perc, "Quartiles (25,50,75):", quart)
if __name__ == "__main__":
    main()
# Output: Q65: Percentiles (10,50,90): [ 7.9 48.5 87.1] Quartiles (25,50,75): [24.25 48.5  74.  ]

# Q66
def find_index(arr, value):
    return np.where(arr == value)[0][0]

def main():
    arr = np.array([1, 2, 3, 4])
    value = 3
    print("Q66:", find_index(arr, value))
if __name__ == "__main__":
    main()
# Output: Q66: 2

# Q67
def sort_array(arr):
    return np.sort(arr)

def main():
    np.random.seed(0)
    arr = np.random.randint(1, 10, 5)
    print("Q67:", sort_array(arr))
if __name__ == "__main__":
    main()
# Output: Q67: [5 6 6 7 9]

# Q68
def filter_greater_20(arr):
    return arr[arr > 20]

def main():
    arr = np.array([10, 25, 15, 30, 5])
    print("Q68:", filter_greater_20(arr))
if __name__ == "__main__":
    main()
# Output: Q68: [25 30]

# Q69
def filter_divisible_3(arr):
    return arr[arr % 3 == 0]

def main():
    arr = np.array([3, 4, 6, 7, 9])
    print("Q69:", filter_divisible_3(arr))
if __name__ == "__main__":
    main()
# Output: Q69: [3 6 9]

# Q70
def filter_between_20_40(arr):
    return arr[(arr >= 20) & (arr <= 40)]

def main():
    arr = np.array([15, 25, 35, 45, 20])
    print("Q70:", filter_between_20_40(arr))
if __name__ == "__main__":
    main()
# Output: Q70: [25 35 20]

# Q71
def check_byte_order(arr):
    return arr.dtype.byteorder

def main():
    arr = np.array([1, 2, 3])
    print("Q71:", check_byte_order(arr))
if __name__ == "__main__":
    main()
# Output: Q71: =

# Q72
def byte_swap(arr):
    return arr.byteswap()

def main():
    arr = np.array([1, 2, 3], dtype=np.int32)
    print("Q72:", byte_swap(arr))
if __name__ == "__main__":
    main()
# Output: Q72: [16777216 33554432 50331648]

Q1: int32
Q2: True
Q3: [1.+2.j 3.+4.j 5.+6.j]
Q4: [1. 2. 3.]
Q5: [1.1234568 2.9876542]
Q6: ((2, 2), 4, dtype('int32'))
Q7: 2
Q8: (4, 12)
Q9: (8, 4)
Q10: ((2, 3), (12, 4))
Q11: [0. 0. 0. 0. 0.]
Q12: [[1. 1. 1.]
 [1. 1. 1.]]
Q13: [0 2 4 6 8]
Q14: [0.   0.25 0.5  0.75 1.  ]
Q15: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Q16: [1 2 3 4]
Q17: [1 2 3]
Q18: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Q19: [[1 2 5]
 [3 4 6]]
Q26: 2
Q27: 6
Q28: [6 8 7]
Q29: [2 3 4 5]
Q30: [[2 3]
 [5 6]]
Q31: [2 6]
Q32: [6 8]
Q33: [2 7]
Q34: [3 5 6]
Q35: [2 6]
Q36: [6 7 8]
Q37: [[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]
Q38: [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
Q39: [[5 6 7]
 [6 7 8]
 [7 8 9]]
Q40: Shapes incompatible
Q41: [2.5 3.5 4.5]
Q42: [3 6]
Q43: [1 0 1]
Q44: [[ 1  3  6]
 [ 4  9 15]]
Q45: [ True False  True]
Q46: [[1 2 3]
 [4 5 6]]
Q47: [1 2 3 4]
Q48: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Q49: [[1, 2], [3, 4], [5, 6]]
Q50: [ 2 99  3  4]
Q51: [5 7 9]
Q52: [3 3 3]
Q53: [ 4 10 18]
Q54: [2. 2. 2.]
Q55: [ 4  9 16]
Q56: [2 1 3